import type { Diagnosis, EditPatch, EditPlan, EditingStrategy, Feedback, Job, JobEvent, Project, ProjectVersion, ProviderCall, SpeechAsset, Timeline, Transcript, VisualEvidence, VoiceDeletionEvent, VoiceProfile, VoiceReferenceQualityReport, WorkflowRun } from "./schemas.js";

/** Domain persistence boundary. Host implementations own paths, databases, atomicity and URI materialization. */
export interface ProjectRepository {
  create(name: string): Promise<{ project: Project; timeline: Timeline; workflow: WorkflowRun; root: string }>;
  listProjectIds(): Promise<string[]>; projectDiskUsage(projectId: string): Promise<number>; prunePreviews(projectId: string, retain: number): Promise<string[]>; sweepTemporaryFiles(projectId: string): Promise<string[]>;
  readProject(projectId: string): Promise<Project>; writeProject(project: Project): Promise<void>; readTimeline(projectId: string): Promise<Timeline>; writeTimeline(projectId: string, timeline: Timeline): Promise<void>; readWorkflow(projectId: string): Promise<WorkflowRun>; writeWorkflow(projectId: string, workflow: WorkflowRun): Promise<void>;
  writeTranscript(projectId: string, transcript: Transcript): Promise<void>; readTranscript(projectId: string, transcriptId: string): Promise<Transcript>; findTranscriptByCacheKey(projectId: string, cacheKey: string): Promise<Transcript | undefined>;
  writeStrategy(projectId: string, strategy: EditingStrategy): Promise<void>; readStrategy(projectId: string, strategyId: string): Promise<EditingStrategy>; writeEditPlan(projectId: string, plan: EditPlan): Promise<void>; readEditPlan(projectId: string, planId: string): Promise<EditPlan>; writeEditPatch(projectId: string, patch: EditPatch): Promise<void>; readEditPatch(projectId: string, patchId: string): Promise<EditPatch>;
  writeVersion(projectId: string, version: ProjectVersion): Promise<void>; readVersion(projectId: string, version: number): Promise<ProjectVersion>; tryReadVersion(projectId: string, version: number): Promise<ProjectVersion | undefined>; listVersions(projectId: string): Promise<ProjectVersion[]>;
  writeFeedback(projectId: string, feedback: Feedback): Promise<void>; listFeedback(projectId: string): Promise<Feedback[]>; writeDiagnosis(projectId: string, diagnosis: Diagnosis): Promise<void>;
  writeSpeechAsset(projectId: string, speech: SpeechAsset): Promise<void>; readSpeechAsset(projectId: string, id: string): Promise<SpeechAsset>; listSpeechAssets(projectId: string): Promise<SpeechAsset[]>; findSpeechAssetByCacheKey(projectId: string, cacheKey: string): Promise<SpeechAsset | undefined>;
  writeVoiceProfile(projectId: string, profile: VoiceProfile): Promise<void>; readVoiceProfile(projectId: string, id: string): Promise<VoiceProfile>; listVoiceProfiles(projectId: string, includeDeleted?: boolean): Promise<VoiceProfile[]>; writeVoiceDeletionEvent(projectId: string, event: VoiceDeletionEvent): Promise<void>;
  writeVoiceReferenceQuality(projectId: string, report: VoiceReferenceQualityReport): Promise<void>; findVoiceReferenceQualityByCacheKey(projectId: string, cacheKey: string): Promise<VoiceReferenceQualityReport | undefined>;
  writeJob(projectId: string, job: Job): Promise<void>; readJob(projectId: string, jobId: string): Promise<Job>; listJobs(projectId: string): Promise<Job[]>; writeJobEvent(projectId: string, event: JobEvent): Promise<void>; writeProviderCall(projectId: string, call: ProviderCall): Promise<void>;
  writeVisualEvidence(projectId: string, evidence: VisualEvidence): Promise<void>; listVisualEvidence(projectId: string): Promise<VisualEvidence[]>;
  copySourceAsset(projectId: string, sourceUri: string, maxBytes: number): Promise<{ relativePath: string; sha256: string; sizeBytes: number }>; resolveProjectFile(projectId: string, relativePath: string): string;
  removeProjectFile(projectId: string, relativePath: string): Promise<void>; writeProjectFile(projectId: string, relativePath: string, data: Uint8Array | string, createOnly?: boolean): Promise<void>; readProjectFile(projectId: string, relativePath: string): Promise<Uint8Array>; projectFileSize(projectId: string, relativePath: string): Promise<number>;
  withLock<T>(projectId: string, fn: () => Promise<T>): Promise<T>;
}
