import React, {useEffect, useState} from 'react';
import {Button, SafeAreaView, ScrollView, StyleSheet, Text, TextInput, TouchableOpacity, View} from 'react-native';
import {mobileHost} from './src/bootstrap';

const screens = ['Home', 'Provider Settings', 'Import', 'Project', 'Proposal', 'Preview', 'Jobs', 'Settings'] as const;
type Screen = typeof screens[number];

export default function App(): React.JSX.Element {
  const [screen, setScreen] = useState<Screen>('Home'); const [status, setStatus] = useState('Starting native host…'); const [projectId, setProjectId] = useState<string>(); const [assetId, setAssetId] = useState<string>(); const [strategyId, setStrategyId] = useState<string>(); const [apiKey, setApiKey] = useState(''); const [model, setModel] = useState('gpt-5.4-mini'); const [prompt, setPrompt] = useState('剪成 30 秒，去掉废话，开头保留最有信息量的一句。');
  useEffect(() => {void mobileHost.then(host => setStatus(`${host.profile.id} ready · no application backend`)).catch(error => setStatus(String(error)));}, []);
  const run = async (label: string, action: () => Promise<unknown>) => { setStatus(`${label}…`); try { const value = await action(); setStatus(`${label} ✓\n${JSON.stringify(value, null, 2).slice(0, 1200)}`); } catch (error) { setStatus(`${label} failed: ${String(error)}`); } };
  const create = () => run('Create project', async () => { const result = await (await mobileHost).facade.createProject('Mobile proof'); setProjectId(result.project.id); return result.project; });
  const importVideo = () => run('Import video', async () => { if (!projectId) throw new Error('Create a project first'); const asset = await (await mobileHost).facade.importVideo(projectId); if (asset) setAssetId(asset.id); return asset; });
  const connect = () => run('Test and save provider', async () => (await mobileHost).facade.connectProvider({schemaVersion: 1, id: 'mobile-openai', kind: 'openai', displayName: 'OpenAI BYOK', baseUrl: 'https://api.openai.com/v1', model, credentialRef: 'provider.mobile-openai', authMode: 'DIRECT_BYOK', reasoning: 'medium', modelDiscovery: 'api-with-static-fallback', enabled: true, metadata: {client: 'native-mobile-proof'}}, apiKey));
  const propose = () => run('Propose edit', async () => { if (!projectId || !assetId) throw new Error('Import a video first'); const host = await mobileHost; const strategy = await host.facade.proposeEdit(projectId, assetId, prompt); setStrategyId(strategy.id); return {strategy, privacyEvidence: host.facade.privacyEvidence()}; });
  const approve = () => run('Approve and apply', async () => { if (!projectId || !strategyId) throw new Error('Create a proposal first'); return (await mobileHost).facade.approveProposal(projectId, strategyId); });
  const preview = () => run('Render preview', async () => { if (!projectId) throw new Error('No project'); return (await mobileHost).facade.renderPreview(projectId); });
  const jobs = () => run('List durable jobs', async () => projectId ? (await mobileHost).facade.listJobs(projectId) : []);
  const exportVideo = () => run('Export video', async () => { if (!projectId) throw new Error('No project'); return (await mobileHost).facade.exportVideo(projectId); });
  return <SafeAreaView style={styles.safe}><View style={styles.header}><Text style={styles.title}>VIDEO AGENT</Text><Text style={styles.meta}>NATIVE HOST PROOF / ZERO SERVER</Text></View><ScrollView horizontal style={styles.nav} contentContainerStyle={styles.navContent}>{screens.map(item => <TouchableOpacity key={item} onPress={() => setScreen(item)} style={[styles.tab, screen === item && styles.active]}><Text style={styles.tabText}>{item}</Text></TouchableOpacity>)}</ScrollView><ScrollView contentContainerStyle={styles.body}><Text style={styles.kicker}>{screen.toUpperCase()}</Text>{screen === 'Home' && <><Text style={styles.heading}>Portable Core.{`\n`}Native media.</Text><Button title="Create local project" onPress={create}/></>}{screen === 'Provider Settings' && <><TextInput secureTextEntry value={apiKey} onChangeText={setApiKey} placeholder="API key (Keychain / Keystore only)" style={styles.input}/><TextInput value={model} onChangeText={setModel} placeholder="Model" style={styles.input}/><Button title="Test Connection + Save" onPress={connect}/><Text style={styles.note}>Direct BYOK is a constrained prototype. The key never enters Project JSON or UI state beyond this transient field.</Text></>}{screen === 'Import' && <Button title="Choose video" onPress={importVideo}/>} {screen === 'Project' && <Text style={styles.mono}>project {projectId ?? '—'}{`\n`}asset {assetId ?? '—'}</Text>}{screen === 'Proposal' && <><TextInput multiline value={prompt} onChangeText={setPrompt} style={[styles.input, styles.prompt]}/><Button title="Generate proposal" onPress={propose}/><View style={styles.gap}/><Button title="Approve + create Version" onPress={approve}/></>}{screen === 'Preview' && <><Button title="Render local preview" onPress={preview}/><View style={styles.gap}/><Button title="Export local video" onPress={exportVideo}/></>}{screen === 'Jobs' && <Button title="Refresh durable jobs" onPress={jobs}/>} {screen === 'Settings' && <Text style={styles.note}>Privacy defaults: Text Only · raw video excluded · local URIs excluded. Permissions are requested only when their action is invoked.</Text>}<View style={styles.console}><Text style={styles.consoleLabel}>RUNTIME</Text><Text selectable style={styles.consoleText}>{status}</Text></View></ScrollView></SafeAreaView>;
}

const styles = StyleSheet.create({safe:{flex:1,backgroundColor:'#0b0c0e'},header:{padding:20,paddingBottom:10,borderBottomWidth:1,borderColor:'#2a2d31'},title:{color:'#f3f1ea',fontSize:22,fontWeight:'800',letterSpacing:2},meta:{color:'#8c929b',fontSize:10,letterSpacing:1.5,marginTop:5},nav:{maxHeight:52},navContent:{paddingHorizontal:12,alignItems:'center'},tab:{paddingHorizontal:11,paddingVertical:9,marginRight:6,borderWidth:1,borderColor:'#282b30'},active:{backgroundColor:'#d8ff48',borderColor:'#d8ff48'},tabText:{fontSize:11,color:'#aeb3bb'},body:{padding:22,paddingBottom:80},kicker:{color:'#d8ff48',fontSize:11,letterSpacing:2,marginBottom:18},heading:{color:'#f3f1ea',fontSize:40,lineHeight:42,fontWeight:'700',marginBottom:28},input:{backgroundColor:'#15171a',color:'#f3f1ea',borderWidth:1,borderColor:'#343840',padding:14,marginBottom:12},prompt:{minHeight:110,textAlignVertical:'top'},note:{color:'#aeb3bb',lineHeight:20,marginTop:18},mono:{color:'#d9dde3',fontFamily:'monospace',lineHeight:22},gap:{height:12},console:{marginTop:28,padding:14,backgroundColor:'#111316',borderLeftWidth:3,borderColor:'#d8ff48'},consoleLabel:{color:'#d8ff48',fontSize:10,letterSpacing:2,marginBottom:8},consoleText:{color:'#abb1ba',fontFamily:'monospace',fontSize:11,lineHeight:17}});
