#!/usr/bin/env node
import { McpServer } from "@modelcontextprotocol/sdk/server/mcp.js";
import { StdioServerTransport } from "@modelcontextprotocol/sdk/server/stdio.js";
import { z } from "zod";
import { secondsToUs } from "../../core/src/index.js";
import { createRuntime } from "../../runtime/src/index.js";

const core = createRuntime();
const server = new McpServer({ name: "video-agent-runtime", version: "0.4.0" }, { capabilities: { logging: {} } });
const outputSchema = z.object({ result: z.unknown() });

function register<T extends z.ZodRawShape>(name: string, description: string, inputSchema: z.ZodObject<T>, handler: (input: z.infer<z.ZodObject<T>>) => Promise<unknown>) {
  server.registerTool(name, { description, inputSchema, outputSchema }, async (input) => {
    try {
      const result = await handler(input as z.infer<z.ZodObject<T>>);
      return { content: [{ type: "text" as const, text: JSON.stringify(result) }], structuredContent: { result } };
    } catch (error) {
      const message = error instanceof Error ? error.message : String(error);
      return { content: [{ type: "text" as const, text: message }], structuredContent: { result: { error: message } }, isError: true };
    }
  });
}

const projectInput = z.object({ projectId: z.string().min(3) });

register("project_create", "Create a durable video project inside the configured workspace.", z.object({ name: z.string().min(1) }), async ({ name }) => core.createProject(name));
register("project_status", "Read project, timeline, and recoverable workflow state.", projectInput, async ({ projectId }) => core.status(projectId));
register("project_open", "Open and validate an existing project by id.", projectInput, async ({ projectId }) => core.status(projectId));
register("video_import", "Copy a source video into the project workspace, hash it, and inspect metadata.", z.object({ projectId: z.string(), sourcePath: z.string().min(1) }), async ({ projectId, sourcePath }) => core.importVideo(projectId, sourcePath));
register("video_inspect", "Return imported video metadata without sending video to a model.", projectInput, async ({ projectId }) => (await core.status(projectId)).project.assets);
register("asr_transcribe", "Transcribe an imported asset into timeline-ready segments and word timestamps.", z.object({ projectId: z.string(), assetId: z.string(), language: z.string().optional(), prompt: z.string().optional(), background: z.boolean().optional() }), async ({ projectId, assetId, language, prompt, background }) => background ? core.enqueueJob(projectId, "asr", { assetId, options: { ...(language ? { language } : {}), ...(prompt ? { prompt } : {}) } }, `asr:${assetId}:${language ?? "auto"}`) : core.transcribe(projectId, assetId, { ...(language ? { language } : {}), ...(prompt ? { prompt } : {}) }));
register("asr_status", "Report active ASR provider capabilities and transcript status.", projectInput, async ({ projectId }) => ({ provider: core.providers.asr.id, model: core.providers.asr.model, capabilities: core.providers.asr.capabilities(), transcriptId: (await core.status(projectId)).project.activeTranscriptId }));
register("transcript_read", "Read the active structured transcript, preserving raw, normalized, and display text.", projectInput, async ({ projectId }) => core.readTranscript(projectId));
register("transcript_quality", "Read low-confidence, alignment, speaker-overlap, silence, music, and language warnings.", projectInput, async ({ projectId }) => core.transcriptQuality(projectId));
register("transcript_enrich", "Run configured alignment and diarization providers, falling back to ASR timing when unavailable.", z.object({ projectId: z.string(), background: z.boolean().optional() }), async ({ projectId, background }) => background ? core.enqueueJob(projectId, "alignment", {}, `enrich:${(await core.status(projectId)).project.activeTranscriptId ?? "none"}`) : core.enrichTranscript(projectId));
register("transcript_search", "Search transcript segments without re-inspecting the full video.", z.object({ projectId: z.string(), query: z.string().min(1) }), async ({ projectId, query }) => core.searchTranscript(projectId, query));
register("transcript_inspect_range", "Read transcript words and segments overlapping a source-time range.", z.object({ projectId: z.string(), startSeconds: z.number().nonnegative(), endSeconds: z.number().positive() }), async ({ projectId, startSeconds, endSeconds }) => {
  const transcript = await core.readTranscript(projectId);
  const startUs = secondsToUs(startSeconds); const endUs = secondsToUs(endSeconds);
  return { words: transcript.words.filter((word) => word.endUs > startUs && word.startUs < endUs), segments: transcript.segments.filter((segment) => segment.endUs > startUs && segment.startUs < endUs) };
});
register("timeline_read", "Read the durable Timeline IR.", projectInput, async ({ projectId }) => (await core.status(projectId)).timeline);
register("timeline_inspect_range", "Read timeline clips overlapping an output-time range.", z.object({ projectId: z.string(), startSeconds: z.number().nonnegative(), endSeconds: z.number().positive() }), async ({ projectId, startSeconds, endSeconds }) => {
  const timeline = (await core.status(projectId)).timeline; const startUs = secondsToUs(startSeconds); const endUs = secondsToUs(endSeconds);
  return timeline.tracks.map((track) => ({ ...track, clips: track.clips.filter((clip) => clip.timelineOutUs > startUs && clip.timelineInUs < endUs) }));
});
register("visual_inspect_range", "Extract on-demand shot changes and representative keyframes for a source range.", z.object({ projectId: z.string(), startSeconds: z.number().nonnegative(), endSeconds: z.number().positive(), background: z.boolean().optional() }), async ({ projectId, startSeconds, endSeconds, background }) => background ? core.enqueueJob(projectId, "visual-analysis", { startUs: secondsToUs(startSeconds), endUs: secondsToUs(endSeconds) }) : core.inspectVisualRange(projectId, secondsToUs(startSeconds), secondsToUs(endSeconds)));
register("strategy_propose", "Propose an explicit EditingStrategy; this does not mutate the timeline.", z.object({ projectId: z.string(), prompt: z.string().min(1), targetDurationSeconds: z.number().positive().max(3600) }), async ({ projectId, prompt, targetDurationSeconds }) => core.proposeStrategy(projectId, prompt, secondsToUs(targetDurationSeconds)));
register("strategy_approve", "Record explicit user approval of a proposed EditingStrategy.", z.object({ projectId: z.string(), strategyId: z.string() }), async ({ projectId, strategyId }) => core.approveStrategy(projectId, strategyId));
register("edit_plan_create", "Create a structured EditPlan from the approved strategy.", projectInput, async ({ projectId }) => core.createEditPlan(projectId));
register("edit_plan_validate", "Run schema and semantic validation without applying a plan.", z.object({ projectId: z.string(), planId: z.string() }), async ({ projectId, planId }) => core.validatePlan(projectId, planId));
register("edit_plan_diff", "Preview the exact timeline diff a plan would produce.", z.object({ projectId: z.string(), planId: z.string() }), async ({ projectId, planId }) => core.diffPlan(projectId, planId));
register("edit_plan_apply", "Transactionally apply a validated plan and create an immutable version.", z.object({ projectId: z.string(), planId: z.string() }), async ({ projectId, planId }) => core.applyPlan(projectId, planId));
register("edit_plan_revert", "Restore a prior immutable version as a new version.", z.object({ projectId: z.string(), version: z.number().int().positive() }), async ({ projectId, version }) => core.restoreVersion(projectId, version));
register("edit_patch_plan", "Plan the smallest range-scoped reversible patch for recent feedback.", projectInput, async ({ projectId }) => core.createPatch(projectId));
register("edit_patch_validate", "Validate patch semantics, declared scope, locality, and base version.", z.object({ projectId: z.string(), patchId: z.string() }), async ({ projectId, patchId }) => core.validatePatch(projectId, patchId));
register("edit_patch_diff", "Preview the exact Timeline diff produced by a PatchPlan.", z.object({ projectId: z.string(), patchId: z.string() }), async ({ projectId, patchId }) => core.diffPatch(projectId, patchId));
register("edit_patch_apply", "Apply a validated PatchPlan as one immutable version.", z.object({ projectId: z.string(), patchId: z.string() }), async ({ projectId, patchId }) => core.applyPatch(projectId, patchId));
register("preview_render", "Render a fast proxy preview, optionally for a partial output range.", z.object({ projectId: z.string(), startSeconds: z.number().nonnegative().optional(), endSeconds: z.number().positive().optional() }), async ({ projectId, startSeconds, endSeconds }) => core.renderPreview(projectId, startSeconds !== undefined && endSeconds !== undefined ? { startUs: secondsToUs(startSeconds), endUs: secondsToUs(endSeconds) } : undefined));
register("preview_status", "Return preview-related workflow state.", projectInput, async ({ projectId }) => (await core.status(projectId)).workflow);
register("feedback_submit", "Normalize and persist review feedback for the active version.", z.object({ projectId: z.string(), message: z.string().min(1), category: z.enum(["pace", "hook", "story_structure", "segment_selection", "ordering", "length", "caption", "visual", "audio", "tts", "narration", "broll", "transition", "specific_cut", "other"]).optional(), startSeconds: z.number().nonnegative().optional(), endSeconds: z.number().positive().optional(), severity: z.enum(["low", "medium", "high"]).optional() }), async ({ projectId, message, category, startSeconds, endSeconds, severity }) => core.submitFeedback(projectId, message, { ...(category ? { category } : {}), ...(startSeconds !== undefined && endSeconds !== undefined ? { range: { startUs: secondsToUs(startSeconds), endUs: secondsToUs(endSeconds) } } : {}), ...(severity ? { severity } : {}) }));
register("workflow_status", "Read the explicit durable workflow state machine.", projectInput, async ({ projectId }) => (await core.status(projectId)).workflow);
register("workflow_diagnose", "Diagnose feedback history and recommend PATCH, REPLAN, ASK_USER, or KEEP_CURRENT.", projectInput, async ({ projectId }) => core.diagnose(projectId));
register("workflow_replan", "Create a new proposed strategy when diagnosis proves the current strategy should be replaced.", projectInput, async ({ projectId }) => core.replan(projectId));
register("version_list", "List immutable applied versions and their provenance.", projectInput, async ({ projectId }) => core.listVersions(projectId));
register("version_compare", "Compare two versions as a structured diff.", z.object({ projectId: z.string(), fromVersion: z.number().int().positive(), toVersion: z.number().int().positive() }), async ({ projectId, fromVersion, toVersion }) => core.compareVersions(projectId, fromVersion, toVersion));
register("version_restore", "Restore a prior version without destroying later history.", z.object({ projectId: z.string(), version: z.number().int().positive() }), async ({ projectId, version }) => core.restoreVersion(projectId, version));
register("tts_list_voices", "List TTS voices and cloning/usage metadata.", z.object({}), async () => core.providers.tts.listVoices?.() ?? []);
register("tts_fit_to_range", "Classify deterministic fit actions without silently applying unreasonable speech acceleration.", z.object({ durationSeconds: z.number().positive(), targetSeconds: z.number().positive(), maxSpeed: z.number().min(1).max(1.5).optional(), allowRewrite: z.boolean().optional(), allowExtend: z.boolean().optional(), allowReplan: z.boolean().optional() }), async ({ durationSeconds, targetSeconds, maxSpeed, allowRewrite, allowExtend, allowReplan }) => core.fitSpeech(secondsToUs(durationSeconds), secondsToUs(targetSeconds), { ...(maxSpeed === undefined ? {} : { maxRate: maxSpeed }), ...(allowRewrite === undefined ? {} : { allowRewrite }), ...(allowExtend === undefined ? {} : { allowExtend }), ...(allowReplan === undefined ? {} : { allowReplan }) }));
register("voice_capabilities", "Report provider-neutral TTS, voice design, authorized cloning, conversion, streaming and timestamp capabilities.", z.object({}), async () => core.voiceCapabilities());
register("voice_models", "List configured voice models without exposing provider credentials.", z.object({}), async () => core.voiceModels());
register("voice_list", "List preset and project VoiceProfiles without reference media or embeddings.", projectInput, async ({ projectId }) => core.listVoices(projectId));
register("voice_reference_analyze", "Analyze an authorized source asset and rank clean 8–15 second reference candidates without enrolling it.", z.object({ projectId: z.string(), assetId: z.string(), speakerId: z.string().optional(), background: z.boolean().optional() }), async ({ projectId, assetId, speakerId, background }) => background ? core.enqueueJob(projectId, "voice-reference-analysis", { assetId, ...(speakerId ? { speakerId } : {}) }, `voice-analysis:${assetId}:${speakerId ?? "all"}`) : core.analyzeVoiceReference(projectId, assetId, speakerId));
register("voice_enroll", "Explicitly enroll an authorized voice reference; never runs from speaker detection alone.", z.object({ projectId: z.string(), assetId: z.string(), name: z.string().min(1), languages: z.array(z.string().min(2)).min(1), authorizationConfirmed: z.boolean(), grantedBy: z.string().min(1), evidence: z.string().min(1), scope: z.string().optional(), speakerId: z.string().optional(), providerAuthorizationId: z.string().optional(), background: z.boolean().optional() }), async ({ projectId, background, scope, speakerId, providerAuthorizationId, ...input }) => { const request = { ...input, ...(scope ? { scope } : {}), ...(speakerId ? { speakerId } : {}), ...(providerAuthorizationId ? { providerAuthorizationId } : {}) }; return background ? core.enqueueJob(projectId, "voice-enroll", request) : core.enrollVoice(projectId, request); });
register("voice_preview", "Generate a review sample for a pending or active VoiceProfile, returning metadata rather than raw reference material.", z.object({ projectId: z.string(), voiceProfileId: z.string(), text: z.string().min(1), language: z.string().min(2), background: z.boolean().optional() }), async ({ background, ...input }) => background ? core.enqueueJob(input.projectId, "voice-preview", input) : core.previewVoice(input.projectId, input));
register("voice_approve", "Activate a VoiceProfile only after the user reviewed its generated sample.", z.object({ projectId: z.string(), voiceProfileId: z.string() }), async ({ projectId, voiceProfileId }) => core.approveVoice(projectId, voiceProfileId));
register("voice_design", "Create a reusable synthetic voice candidate from a description instead of cloning a person.", z.object({ projectId: z.string(), description: z.string().min(1), language: z.string().min(2), sampleText: z.string().min(1), tone: z.string().optional(), pace: z.enum(["slow", "moderate", "fast"]).optional(), agePresentation: z.string().optional(), energy: z.string().optional(), style: z.string().optional(), background: z.boolean().optional() }), async ({ projectId, background, ...request }) => background ? core.enqueueJob(projectId, "voice-design", request) : core.designVoice(projectId, request));
register("voice_design_preview", "Generate a sample for a designed VoiceProfile before activation.", z.object({ projectId: z.string(), voiceProfileId: z.string(), text: z.string().min(1), language: z.string().min(2) }), async (input) => core.previewVoice(input.projectId, input));
register("voice_delete", "Delete a VoiceProfile, derived representations and caches, and request remote deletion when supported.", z.object({ projectId: z.string(), voiceProfileId: z.string() }), async ({ projectId, voiceProfileId }) => core.deleteVoice(projectId, voiceProfileId));
register("tts_generate", "Generate a provenance-rich SpeechAsset from an active VoiceProfile without bypassing Timeline for edits.", z.object({ projectId: z.string(), voiceProfileId: z.string(), text: z.string().min(1), language: z.string().min(2), speed: z.number().min(0.5).max(1.5).optional(), background: z.boolean().optional() }), async ({ projectId, background, speed, ...input }) => { const request = { ...input, ...(speed === undefined ? {} : { speed }) }; return background ? core.enqueueJob(projectId, "voice-preview", request) : core.generateSpeech(projectId, request); });
register("tts_preview", "Generate speech preview metadata for review.", z.object({ projectId: z.string(), voiceProfileId: z.string(), text: z.string().min(1), language: z.string().min(2) }), async (input) => core.previewVoice(input.projectId, input));
register("speech_replace", "Classify caption-only versus authorized audio replacement and apply it through EditPatch and Version.", z.object({ projectId: z.string(), startSeconds: z.number().nonnegative(), endSeconds: z.number().positive(), replacementText: z.string().min(1), voiceProfileId: z.string().optional(), language: z.string().min(2), mode: z.enum(["auto", "caption-only", "audio"]).optional(), allowExtend: z.boolean().optional() }), async ({ projectId, startSeconds, endSeconds, voiceProfileId, mode, allowExtend, ...input }) => core.replaceSpeech(projectId, { ...input, startUs: secondsToUs(startSeconds), endUs: secondsToUs(endSeconds), ...(voiceProfileId ? { voiceProfileId } : {}), ...(mode ? { mode } : {}), ...(allowExtend === undefined ? {} : { allowExtend }) }));
register("dubbing_generate", "Generate multilingual DubbingTrack clips linked to source segments, translations, SpeechAssets and VoiceProfiles.", z.object({ projectId: z.string(), language: z.string().min(2), segments: z.array(z.object({ sourceSegmentId: z.string(), translatedText: z.string().min(1), voiceProfileId: z.string() })).min(1), allowExtend: z.boolean().optional(), background: z.boolean().optional() }), async ({ projectId, background, allowExtend, ...input }) => { const request = { ...input, ...(allowExtend === undefined ? {} : { allowExtend }) }; return background ? core.enqueueJob(projectId, "dubbing", request) : core.generateDubbing(projectId, request); });
register("narration_add", "Alias for timeline-aware narration generation through SpeechAsset and Version.", z.object({ projectId: z.string(), text: z.string().min(1), voiceId: z.string(), language: z.string(), timelineInSeconds: z.number().nonnegative() }), async ({ projectId, text, voiceId, language, timelineInSeconds }) => core.addNarration(projectId, { text, voiceId, language, timelineInUs: secondsToUs(timelineInSeconds) }));
register("audio_add_narration", "Generate a TTS asset, add an editable narration clip and captions, and explicitly enable ducking.", z.object({ projectId: z.string(), text: z.string().min(1), voiceId: z.string(), language: z.string(), timelineInSeconds: z.number().nonnegative(), targetDurationSeconds: z.number().positive().optional(), actionOnOverflow: z.enum(["extend", "fail"]).optional() }), async ({ projectId, text, voiceId, language, timelineInSeconds, targetDurationSeconds, actionOnOverflow }) => core.addNarration(projectId, { text, voiceId, language, timelineInUs: secondsToUs(timelineInSeconds), ...(targetDurationSeconds ? { targetDurationUs: secondsToUs(targetDurationSeconds) } : {}), ...(actionOnOverflow ? { actionOnOverflow } : {}) }));
register("final_approve", "Record explicit final approval of the active version.", projectInput, async ({ projectId }) => core.approveFinal(projectId));
register("export_video", "Render the active version at final quality only after explicit final approval.", projectInput, async ({ projectId }) => core.exportVideo(projectId));
register("system_status", "Check FFmpeg and configured planner, ASR, alignment, diarization, voice/TTS, and visual providers.", z.object({}), async () => core.systemStatus());
register("job_status", "Read one durable long-running job.", z.object({ projectId: z.string(), jobId: z.string() }), async ({ projectId, jobId }) => core.jobStatus(projectId, jobId));
register("job_list", "List durable jobs for a project.", projectInput, async ({ projectId }) => core.listJobs(projectId));
register("job_cancel", "Request cancellation and propagate it to the active provider or child process.", z.object({ projectId: z.string(), jobId: z.string() }), async ({ projectId, jobId }) => core.cancelJob(projectId, jobId));

await server.connect(new StdioServerTransport());
